# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[main]
font=JetBrainsMono Nerd Font:style=Medium:size=12
font-bold=JetBrainsMono Nerd Font:style=Bold:size=12
font-italic=JetBrainsMono Nerd Font:style=Medium Italic:size=12
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=12

pad=0x0 center

[scrollback]
lines=10000
indicator-format=line

[cursor]
style=beam
blink=yes
blink-rate=800
beam-thickness=2.5
unfocused-style=hollow

[mouse]
hide-when-typing=yes

[bell]
visual=yes
system=no
urgent=no
notify=no

[colors-dark]
alpha=0.80
alpha-mode=matching
blur=yes
background=000000
foreground=dfdfdd

selection-foreground=000000
selection-background=eebebe

flash=e78284
flash-alpha=0.5

regular0=000000
regular1=e78284
regular2=b6e0a4
regular3=fab387
regular4=9fcbfc
regular5=c8a4e0
regular6=9bbfbf
regular7=dfdfdd

bright0=6a707f
bright1=eebebe
bright2=b6e0a4
bright3=e0d8a4
bright4=9fcbfc
bright5=c8a4e0
bright6=9bbfbf
bright7=dfdfdd

[regex:hashes]
regex=([a-fA-F0-9]{7,40})

[regex:paths]
regex=([a-zA-Z0-9._~/-]*[./][a-zA-Z0-9._~/-]*:[0-9]+)
launch=/home/buck/.config/foot/open-match.sh ${match}

[key-bindings]
font-increase=Control+equal Control+plus Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=Shift+Insert

regex-copy=[hashes] Control+Shift+g
regex-launch=[paths] Control+Shift+p
pipe-command-output=[sh -c "f=$(mktemp); cat - > $f; footclient less -R $f; rm $f"] Control+Shift+t

